### ISSUE TITLE
How to access license url?

### ISSUE THREAD

**Issue by TiheChen** [a16z/a16z-contracts#21]
I deploy a NFT with CantNotBeEvil on local node.
when I tried to get the lecense url it returned `ar://zmc1WTspIhFyVY82bwfAIcIExLFH5lUcHHUN0wXg4W8/0`
how can I read the pdf on browser or how to read the license?

**Comment by Blauyourmind** [comment]
Append arweave.net before the hash. So: arweave.net/zmc1WTspIhFyVY82bwfAIcIExLFH5lUcHHUN0wXg4W8/0. Then place that in your browser.
