### ISSUE TITLE
Text versions of the License PDFs

### ISSUE THREAD

**Issue by HazardJ** [a16z/a16z-contracts#3]
Hi all!
Great initiative!  
Are there text versions of the License PDFs available?  Word or otherwise.  (I see doc ids such as US-DOCS\133478262.6)
I'm converting these into ProseObject format and scraping the (images of) PDFs is a bit awkward/inaccurate.  
Thanks.  
Work in progress will be at www.github.com/CommonAccord/a16z-contracts/.

**Comment by fmhall** [comment]
Done with #18
