### ISSUE TITLE
Licensing the licences

### ISSUE THREAD

**Issue by Daimon-Law** [a16z/a16z-contracts#4]
Great work here with lots to think about. 

Before we all get into the weeds though, could you please update the Github repo to reflect the use/modification rights of the licence documents themselves? Without clarifying the nature of the open source licensing, the assumption is that a16z still retains copyright and other IP associated with these licence terms.

**Comment by HazardJ** [comment]
:)

**Comment by Blauyourmind** [comment]
Thanks for pointing this out! Just updated the repo. The text of the Licenses is made freely available to the public under the terms of CC0 1.0 Universal.
